apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-http
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-http
        version: v1
    spec:
      containers:
      - name: node-http
        image: hegde9/node-http:latest
        ports:
        - containerPort: 8001
          protocol: TCP
        env:
          - name: msg
            value: "hello from nodejs!!!!!"