apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-http
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: node-http
        version: v1
    spec:
      containers:
      - name: node-http
        image: your_image_path
        ports:
        - containerPort: 8001
          protocol: TCP
