apiVersion: v1
kind: Service
metadata:
  name: node-http
spec:
  type: NodePort
  ports:
    - port: 8001
      targetPort: 8001
      nodePort: 30080
  selector:
<<<<<<< HEAD
    app: node-http
=======
    app: node-http
>>>>>>> 8d2f341e570523811a7512f48bb54ae472b2f118
